import type { Ingreso, Lote, OrigenMonte, Paquete, Produccion } from '@/types/produccion';


export const origenes: OrigenMonte[] = [
  {
    id: 'ori1',
    nombre: 'Monte Norte',
    establecimiento: 'Establecimiento Norte',
    localidad: 'Posadas',
    provincia: 'Misiones',
    latitud: -27.3621,
    longitud: -55.9009,
    observaciones: 'Origen de demostración asociado al remito 4587.',
    activo: true,
  },
  {
    id: 'ori2',
    nombre: 'Monte Sur',
    establecimiento: 'Establecimiento Sur',
    localidad: 'Candelaria',
    provincia: 'Misiones',
    latitud: -27.4592,
    longitud: -55.7454,
    observaciones: 'Origen de demostración.',
    activo: true,
  },
];

export const ingresos: Ingreso[] = [
  {
    id: 'ing1',
    fecha: '08/12/2024',
    proveedor: 'Forestal Demo',
    remito: '4587',
    origenId: 'ori1',
    producto: 'Rollo de Pino',
    pesoBruto: 34200,
    tara: 12200,
    pesoNeto: 22000,
    observaciones: 'Madera de buena calidad, sin manchas.',
    transportista: 'Transportes del Bosque',
    chofer: 'Juan Pérez',
    patenteCamion: 'AB123CD',
    patenteAcoplado: 'XY987ZW',
    estado: 'ASIGNADO',
  },
  {
    id: 'ing2',
    fecha: '06/12/2024',
    proveedor: 'Maderera Sur',
    remito: '4521',
    origenId: 'ori2',
    producto: 'Rollo de Pino',
    pesoBruto: 31000,
    tara: 11500,
    pesoNeto: 19500,
    observaciones: '',
    transportista: 'Logística Maderera',
    chofer: 'Carlos Gómez',
    patenteCamion: 'CD456EF',
    patenteAcoplado: 'AB456CD',
    estado: 'REGISTRADO',
  },
];

export const lotes: Lote[] = [
  {
    id: 'l1',
    numero: '850',
    fecha: '08/12/2024',
    ingresoId: 'ing1',
    fila: '4',
    diametro: 30,
    largo: 3.05,
    cantidadRollos: 18,
    observaciones: 'Lote de primera calidad.',
    estado: 'EN_PROCESO',
  },
  {
    id: 'l2',
    numero: '851',
    fecha: '09/12/2024',
    ingresoId: 'ing2',
    fila: '5',
    diametro: 28,
    largo: 3.05,
    cantidadRollos: 15,
    observaciones: '',
    estado: 'DISPONIBLE',
  },
];

export const producciones: Produccion[] = [
  {
    id: 'prod1',
    fecha: '10/12/2024',
    turno: 'Mañana',
    sector: 'Aserradero',
    linea: 'Línea principal',
    loteId: 'l1',
    cantidadProcesada: 22000,
    unidadMedida: 'kg',
    observaciones: 'Producción normal del turno mañana.',
    paquetes: [
      {
        id: 'paq1',
        codigo: 'LIN714438',
        fecha: '10/12/2024',
        loteId: 'l1',
        produccionId: 'prod1',
        producto: 'PINO CEPILLADO PARA LOWER',
        cantidadPiezas: 750,
        espesor: 19.05,
        ancho: 65.1,
        largo: 3050,
        p2: 1202.83,
        m2: 148.97,
        m3: 2.84,
        deposito: '47',
        aptoPara: 'LOWER',
        linea: 'Línea principal',
        turno: 'Mañana',
        observaciones: '',
        estado: 'MADERA_VERDE',
        publicToken: 'demo-lin714438-850',
      },
      {
        id: 'paq2',
        codigo: 'LIN714439',
        fecha: '10/12/2024',
        loteId: 'l1',
        produccionId: 'prod1',
        producto: 'PINO CEPILLADO PARA LOWER',
        cantidadPiezas: 680,
        espesor: 19.05,
        ancho: 65.1,
        largo: 3050,
        p2: 1090.56,
        m2: 135.12,
        m3: 2.575,
        deposito: '47',
        aptoPara: 'LOWER',
        linea: 'Línea principal',
        turno: 'Mañana',
        observaciones: '',
        estado: 'MADERA_VERDE',
        publicToken: 'demo-lin714439-850',
      },
      {
        id: 'paq3',
        codigo: 'LIN714440',
        fecha: '10/12/2024',
        loteId: 'l1',
        produccionId: 'prod1',
        producto: 'PINO CEPILLADO PARA LOWER',
        cantidadPiezas: 720,
        espesor: 19.05,
        ancho: 65.1,
        largo: 3050,
        p2: 1154.71,
        m2: 143.01,
        m3: 2.726,
        deposito: '47',
        aptoPara: 'LOWER',
        linea: 'Línea principal',
        turno: 'Mañana',
        observaciones: '',
        estado: 'MADERA_VERDE',
        publicToken: 'demo-lin714440-850',
      },
    ],
  },
];

export const paquetes: Paquete[] = producciones.flatMap((p) => p.paquetes);
